import { defineConfig } from 'vite'
import { resolve, join } from 'path'
import { fileURLToPath } from 'url'
import { readdirSync, existsSync } from 'fs'
import { markdownPlugin } from './vite-plugin-markdown.js'

const __dirname = fileURLToPath(new URL('.', import.meta.url))

// Find resume HTML files (including language variants)
const resumeDir = resolve(__dirname, 'resume')
const resumeEntries = {}
const resumeHtmlPath = join(resumeDir, 'index.html')
if (existsSync(resumeHtmlPath)) {
  resumeEntries.resume = resumeHtmlPath
}
// Check for language variants (e.g., index.zh-tw.html)
try {
  const resumeFiles = readdirSync(resumeDir)
  const langPattern = /^index\.([a-z]{2}(-[a-z]{2})?)\.html$/i
  for (const file of resumeFiles) {
    const match = file.match(langPattern)
    if (match) {
      const lang = match[1].toLowerCase()
      const langHtmlPath = join(resumeDir, file)
      resumeEntries[`resume/${lang}`] = langHtmlPath
    }
  }
} catch (err) {
  // Ignore errors
}

// https://vite.dev/config/
export default defineConfig({
  // Base public path when served in production
  base: '/',
  
  // Markdown plugin configuration
  plugins: [
    markdownPlugin(),
  ],
  
  // Development server options
  server: {
    port: 5173,
    open: true,
    host: true,
  },
  
  // Build options
  build: {
    outDir: 'dist',
    sourcemap: true,
    // Target modern browsers
    target: 'esnext',
    emptyOutDir: true,
    // Entry points - articles are generated by the markdown plugin during build
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        // Include resume pages (they have their own HTML files)
        ...resumeEntries,
        // Include 404 page
        '404': resolve(__dirname, '404.html'),
      },
    }
  },
  
  // Preview server options
  preview: {
    port: 4173,
    host: true,
  },
})
